name: get_time_ago
description: A new Flutter plugin to format DateTime in seconds ago, minutes ago, hours ago, days ago and date.
version: 1.0.1
homepage: https://pub.dev/packages/get_time_ago

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8
