name: get_time_ago
description: A new Flutter package for getting time formats in secons, minutes, hours, days and date.
version: 0.0.4
homepage: https://github.com/nixrajput/get-time-ago

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter