name: get_time_ago
description: A Flutter package to convert and format `DateTime` object into `get_time_ago` format to get String like `10 seconds ago`, `a minute ago`, `7 hours ago`, etc.
version: 1.1.4
homepage: https://github.com/nixrajput
repository: https://github.com/nixrajput/get-time-ago
issue_tracker: https://github.com/nixrajput/get-time-ago/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
