name: get_time_ago
description: A new Flutter plugin to format DateTime in seconds ago, minutes ago, hours ago, days ago and date.
version: 0.1.2
homepage: https://github.com/nixrajput/get-time-ago

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nixlab.get_time_ago
        pluginClass: GetTimeAgoPlugin
      ios:
        pluginClass: GetTimeAgoPlugin