name: get_time_ago
description: A Dart package to convert and format `DateTime` object into `get_time_ago` format to get String like `10 seconds ago`, `a minute ago`, `7 hours ago`, etc.

version: 1.3.1

homepage: https://pub.dev/packages/get_time_ago
repository: https://github.com/nixrajput/get-time-ago
issue_tracker: https://github.com/nixrajput/get-time-ago/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  intl: ">=0.18.0 <0.20.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
