name: get_time_ago
description: A Flutter plugin to format DateTime in seconds ago, minutes ago, hours ago, days ago and date.
version: 1.0.7
homepage: https://github.com/nixrajput/get-time-ago

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
