name: get_time_ago
description: A new Flutter plugin to format DateTime in seconds ago, minutes ago, hours ago, days ago and date.
version: 0.1.7
homepage: https://github.com/nixrajput/get-time-ago

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  test: ^1.16.0
